
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Munin Munin :: s18277980 :: s18277980</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Auto-generated by Munin">

    <link rel="shortcut icon" type="image/x-icon" href="../../static/img/favicon.ico" />
    <link rel="icon" type="image/png" href="../../static/img/favicon.png" />
    <link href="../../static/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../../static/css/style-munstrap.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="sr-only">Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="../.."><span class="munin-icon"></span> MUNIN</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="../..">Home</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Problems <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="../../problems.html#critical"><span class="badge alert-danger pull-right">0</span>Critical</a></li>
                <li><a href="../../problems.html#warnings"><span class="badge alert-warning pull-right">0</span>Warning</a></li>
                <li><a href="../../problems.html#unknowns"><span class="badge alert-info pull-right">0</span>Unknown</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Groups <b class="caret"></b></a>
              <ul class="dropdown-menu">

                  <li><a href="../../s18277980/index.html">s18277980</a></li>

              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hosts <b class="caret"></b></a>
              <ul class="dropdown-menu">



                      <li><a href="../../s18277980/s18277980/index.html">s18277980</a></li>



              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <b class="caret"></b></a>
              <ul class="dropdown-menu" style="min-width: 300px;">

                  <li>
                    <a href="../../disk-day.html">disk</a>
					<div style="margin-left: 25px; margin-bottom: 5px;">
						<a href="../../disk-day.html"><span class="badge">d</span></a>
						<a href="../../disk-week.html"><span class="badge">w</span></a>
						<a href="../../disk-month.html"><span class="badge">m</span></a>
						<a href="../../disk-year.html"><span class="badge">y</span></a>
					</div>
                  </li>

                  <li>
                    <a href="../../munin-day.html">munin</a>
					<div style="margin-left: 25px; margin-bottom: 5px;">
						<a href="../../munin-day.html"><span class="badge">d</span></a>
						<a href="../../munin-week.html"><span class="badge">w</span></a>
						<a href="../../munin-month.html"><span class="badge">m</span></a>
						<a href="../../munin-year.html"><span class="badge">y</span></a>
					</div>
                  </li>

                  <li>
                    <a href="../../mysql-day.html">mysql</a>
					<div style="margin-left: 25px; margin-bottom: 5px;">
						<a href="../../mysql-day.html"><span class="badge">d</span></a>
						<a href="../../mysql-week.html"><span class="badge">w</span></a>
						<a href="../../mysql-month.html"><span class="badge">m</span></a>
						<a href="../../mysql-year.html"><span class="badge">y</span></a>
					</div>
                  </li>

                  <li>
                    <a href="../../mysql2-day.html">mysql2</a>
					<div style="margin-left: 25px; margin-bottom: 5px;">
						<a href="../../mysql2-day.html"><span class="badge">d</span></a>
						<a href="../../mysql2-week.html"><span class="badge">w</span></a>
						<a href="../../mysql2-month.html"><span class="badge">m</span></a>
						<a href="../../mysql2-year.html"><span class="badge">y</span></a>
					</div>
                  </li>

                  <li>
                    <a href="../../network-day.html">network</a>
					<div style="margin-left: 25px; margin-bottom: 5px;">
						<a href="../../network-day.html"><span class="badge">d</span></a>
						<a href="../../network-week.html"><span class="badge">w</span></a>
						<a href="../../network-month.html"><span class="badge">m</span></a>
						<a href="../../network-year.html"><span class="badge">y</span></a>
					</div>
                  </li>

                  <li>
                    <a href="../../nginx-day.html">nginx</a>
					<div style="margin-left: 25px; margin-bottom: 5px;">
						<a href="../../nginx-day.html"><span class="badge">d</span></a>
						<a href="../../nginx-week.html"><span class="badge">w</span></a>
						<a href="../../nginx-month.html"><span class="badge">m</span></a>
						<a href="../../nginx-year.html"><span class="badge">y</span></a>
					</div>
                  </li>

                  <li>
                    <a href="../../postfix-day.html">postfix</a>
					<div style="margin-left: 25px; margin-bottom: 5px;">
						<a href="../../postfix-day.html"><span class="badge">d</span></a>
						<a href="../../postfix-week.html"><span class="badge">w</span></a>
						<a href="../../postfix-month.html"><span class="badge">m</span></a>
						<a href="../../postfix-year.html"><span class="badge">y</span></a>
					</div>
                  </li>

                  <li>
                    <a href="../../processes-day.html">processes</a>
					<div style="margin-left: 25px; margin-bottom: 5px;">
						<a href="../../processes-day.html"><span class="badge">d</span></a>
						<a href="../../processes-week.html"><span class="badge">w</span></a>
						<a href="../../processes-month.html"><span class="badge">m</span></a>
						<a href="../../processes-year.html"><span class="badge">y</span></a>
					</div>
                  </li>

                  <li>
                    <a href="../../samba-day.html">samba</a>
					<div style="margin-left: 25px; margin-bottom: 5px;">
						<a href="../../samba-day.html"><span class="badge">d</span></a>
						<a href="../../samba-week.html"><span class="badge">w</span></a>
						<a href="../../samba-month.html"><span class="badge">m</span></a>
						<a href="../../samba-year.html"><span class="badge">y</span></a>
					</div>
                  </li>

                  <li>
                    <a href="../../system-day.html">system</a>
					<div style="margin-left: 25px; margin-bottom: 5px;">
						<a href="../../system-day.html"><span class="badge">d</span></a>
						<a href="../../system-week.html"><span class="badge">w</span></a>
						<a href="../../system-month.html"><span class="badge">m</span></a>
						<a href="../../system-year.html"><span class="badge">y</span></a>
					</div>
                  </li>

              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

	<div class="container">


<ol class="breadcrumb">

	<li>

	  <a href="../..">
		<span class="glyphicon glyphicon-home"></span> Home
	  </a>

	</li>

	<li>

	  <a href="../index.html">
		s18277980
	  </a>

	</li>

	<li>


		s18277980


	</li>

</ol>









    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">

        <li>
    <a href="#overview" id="overview">overview</a>
        </li>

        <li  class="active" >
	  <a href="#disk" data-toggle="tab">disk</a>
        </li>

        <li >
	  <a href="#munin" data-toggle="tab">munin</a>
        </li>

        <li >
	  <a href="#mysql" data-toggle="tab">mysql</a>
        </li>

        <li >
	  <a href="#mysql2" data-toggle="tab">mysql2</a>
        </li>

        <li >
	  <a href="#network" data-toggle="tab">network</a>
        </li>

        <li >
	  <a href="#nginx" data-toggle="tab">nginx</a>
        </li>

        <li >
	  <a href="#postfix" data-toggle="tab">postfix</a>
        </li>

        <li >
	  <a href="#processes" data-toggle="tab">processes</a>
        </li>

        <li >
	  <a href="#samba" data-toggle="tab">samba</a>
        </li>

        <li >
	  <a href="#system" data-toggle="tab">system</a>
        </li>

    </ul>

    <div id="my-tab-content" class="tab-content">

        <div class="tab-pane fade in active" id="disk">

            <div class="row">
              <div class="col-md-6">
                <a href="df.html">
                  <img class="img-responsive i"
                   src="image.php?df-day"
                   alt="Disk usage in percent"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="df.html">
                  <img class="img-responsive i"
                   src="image.php?df-week"
                   alt="Disk usage in percent"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="quota_usage_.html">
                  <img class="img-responsive i"
                   src="image.php?quota_usage_-day"
                   alt="Filesystem usage by user on usage"
                       width="491"
                   height="251"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="quota_usage_.html">
                  <img class="img-responsive i"
                   src="image.php?quota_usage_-week"
                   alt="Filesystem usage by user on usage"
                   width="491"
                   height="251"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="df_inode.html">
                  <img class="img-responsive i"
                   src="image.php?df_inode-day"
                   alt="Inode usage in percent"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="df_inode.html">
                  <img class="img-responsive i"
                   src="image.php?df_inode-week"
                   alt="Inode usage in percent"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

        </div>

        <div class="tab-pane fade " id="munin">

            <div class="row">
              <div class="col-md-6">
                <a href="munin_stats.html">
                  <img class="img-responsive i"
                   src="image.php?munin_stats-day"
                   alt="Munin processing time"
                       width="491"
                   height="311"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="munin_stats.html">
                  <img class="img-responsive i"
                   src="image.php?munin_stats-week"
                   alt="Munin processing time"
                   width="491"
                   height="311"/>
                </a>
              </div>
            </div>

        </div>

        <div class="tab-pane fade " id="mysql">

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_isam_space_information_schema.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_isam_space_information_schema-day"
                   alt="MySQL &quot;information-schema&quot; isam/myisam table-space usage"
                       width="491"
                   height="251"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_isam_space_information_schema.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_isam_space_information_schema-week"
                   alt="MySQL &quot;information-schema&quot; isam/myisam table-space usage"
                   width="491"
                   height="251"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_isam_space_mysql.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_isam_space_mysql-day"
                   alt="MySQL &quot;mysql&quot; isam/myisam table-space usage"
                       width="491"
                   height="515"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_isam_space_mysql.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_isam_space_mysql-week"
                   alt="MySQL &quot;mysql&quot; isam/myisam table-space usage"
                   width="491"
                   height="515"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_isam_space_s6112a.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_isam_space_s6112a-day"
                   alt="MySQL &quot;s6112a&quot; isam/myisam table-space usage"
                       width="491"
                   height="875"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_isam_space_s6112a.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_isam_space_s6112a-week"
                   alt="MySQL &quot;s6112a&quot; isam/myisam table-space usage"
                   width="491"
                   height="875"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_isam_space_s6113a_wordpress.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_isam_space_s6113a_wordpress-day"
                   alt="MySQL &quot;s6113a-wordpress&quot; isam/myisam table-space usage"
                       width="491"
                   height="251"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_isam_space_s6113a_wordpress.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_isam_space_s6113a_wordpress-week"
                   alt="MySQL &quot;s6113a-wordpress&quot; isam/myisam table-space usage"
                   width="491"
                   height="251"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_isam_space_s6114a_wordpress.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_isam_space_s6114a_wordpress-day"
                   alt="MySQL &quot;s6114a-wordpress&quot; isam/myisam table-space usage"
                       width="491"
                   height="251"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_isam_space_s6114a_wordpress.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_isam_space_s6114a_wordpress-week"
                   alt="MySQL &quot;s6114a-wordpress&quot; isam/myisam table-space usage"
                   width="491"
                   height="251"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_isam_space_s6115a_wordpress.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_isam_space_s6115a_wordpress-day"
                   alt="MySQL &quot;s6115a-wordpress&quot; isam/myisam table-space usage"
                       width="491"
                   height="251"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_isam_space_s6115a_wordpress.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_isam_space_s6115a_wordpress-week"
                   alt="MySQL &quot;s6115a-wordpress&quot; isam/myisam table-space usage"
                   width="491"
                   height="251"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_isam_space_s6116a_wordpress.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_isam_space_s6116a_wordpress-day"
                   alt="MySQL &quot;s6116a-wordpress&quot; isam/myisam table-space usage"
                       width="491"
                   height="251"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_isam_space_s6116a_wordpress.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_isam_space_s6116a_wordpress-week"
                   alt="MySQL &quot;s6116a-wordpress&quot; isam/myisam table-space usage"
                   width="491"
                   height="251"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_innodb.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb-day"
                   alt="MySQL InnoDB free tablespace"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_innodb.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb-week"
                   alt="MySQL InnoDB free tablespace"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_queries.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_queries-day"
                   alt="MySQL queries"
                       width="491"
                   height="347"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_queries.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_queries-week"
                   alt="MySQL queries"
                   width="491"
                   height="347"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_slowqueries.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_slowqueries-day"
                   alt="MySQL slow queries"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_slowqueries.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_slowqueries-week"
                   alt="MySQL slow queries"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_threads.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_threads-day"
                   alt="MySQL threads"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_threads.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_threads-week"
                   alt="MySQL threads"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_bytes.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_bytes-day"
                   alt="MySQL throughput"
                       width="491"
                   height="287"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_bytes.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_bytes-week"
                   alt="MySQL throughput"
                   width="491"
                   height="287"/>
                </a>
              </div>
            </div>

        </div>

        <div class="tab-pane fade " id="mysql2">

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_bin_relay_log.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_bin_relay_log-day"
                   alt="Binary/Relay Logs"
                       width="491"
                   height="311"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_bin_relay_log.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_bin_relay_log-week"
                   alt="Binary/Relay Logs"
                   width="491"
                   height="311"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_commands.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_commands-day"
                   alt="Command Counters"
                       width="491"
                   height="383"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_commands.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_commands-week"
                   alt="Command Counters"
                   width="491"
                   height="383"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_connections.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_connections-day"
                   alt="Connections"
                       width="491"
                   height="335"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_connections.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_connections-week"
                   alt="Connections"
                   width="491"
                   height="335"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_files_tables.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_files_tables-day"
                   alt="Files and tables"
                       width="491"
                   height="311"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_files_tables.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_files_tables-week"
                   alt="Files and tables"
                   width="491"
                   height="311"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_innodb_bpool.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_bpool-day"
                   alt="InnoDB Buffer Pool"
                       width="491"
                   height="311"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_innodb_bpool.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_bpool-week"
                   alt="InnoDB Buffer Pool"
                   width="491"
                   height="311"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_innodb_bpool_act.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_bpool_act-day"
                   alt="InnoDB Buffer Pool Activity"
                       width="491"
                   height="311"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_innodb_bpool_act.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_bpool_act-week"
                   alt="InnoDB Buffer Pool Activity"
                   width="491"
                   height="311"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_innodb_insert_buf.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_insert_buf-day"
                   alt="InnoDB Insert Buffer"
                       width="491"
                   height="299"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_innodb_insert_buf.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_insert_buf-week"
                   alt="InnoDB Insert Buffer"
                   width="491"
                   height="299"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_innodb_io.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_io-day"
                   alt="InnoDB IO"
                       width="491"
                   height="311"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_innodb_io.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_io-week"
                   alt="InnoDB IO"
                   width="491"
                   height="311"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_innodb_io_pend.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_io_pend-day"
                   alt="InnoDB IO Pending"
                       width="491"
                   height="347"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_innodb_io_pend.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_io_pend-week"
                   alt="InnoDB IO Pending"
                   width="491"
                   height="347"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_innodb_log.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_log-day"
                   alt="InnoDB Log"
                       width="491"
                   height="299"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_innodb_log.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_log-week"
                   alt="InnoDB Log"
                   width="491"
                   height="299"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_innodb_rows.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_rows-day"
                   alt="InnoDB Row Operations"
                       width="491"
                   height="323"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_innodb_rows.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_rows-week"
                   alt="InnoDB Row Operations"
                   width="491"
                   height="323"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_innodb_semaphores.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_semaphores-day"
                   alt="InnoDB Semaphores"
                       width="491"
                   height="299"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_innodb_semaphores.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_semaphores-week"
                   alt="InnoDB Semaphores"
                   width="491"
                   height="299"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_innodb_tnx.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_tnx-day"
                   alt="InnoDB Transactions"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_innodb_tnx.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_innodb_tnx-week"
                   alt="InnoDB Transactions"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_myisam_indexes.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_myisam_indexes-day"
                   alt="MyISAM Indexes"
                       width="491"
                   height="311"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_myisam_indexes.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_myisam_indexes-week"
                   alt="MyISAM Indexes"
                   width="491"
                   height="311"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_network_traffic.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_network_traffic-day"
                   alt="Network Traffic"
                       width="491"
                   height="287"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_network_traffic.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_network_traffic-week"
                   alt="Network Traffic"
                   width="491"
                   height="287"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_qcache.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_qcache-day"
                   alt="Query Cache"
                       width="491"
                   height="323"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_qcache.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_qcache-week"
                   alt="Query Cache"
                   width="491"
                   height="323"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_qcache_mem.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_qcache_mem-day"
                   alt="Query Cache Memory"
                       width="491"
                   height="287"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_qcache_mem.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_qcache_mem-week"
                   alt="Query Cache Memory"
                   width="491"
                   height="287"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_replication.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_replication-day"
                   alt="Replication"
                       width="491"
                   height="323"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_replication.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_replication-week"
                   alt="Replication"
                   width="491"
                   height="323"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_select_types.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_select_types-day"
                   alt="Select types"
                       width="491"
                   height="335"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_select_types.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_select_types-week"
                   alt="Select types"
                   width="491"
                   height="335"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_slow.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_slow-day"
                   alt="Slow Queries"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_slow.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_slow-week"
                   alt="Slow Queries"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_sorts.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_sorts-day"
                   alt="Sorts"
                       width="491"
                   height="311"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_sorts.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_sorts-week"
                   alt="Sorts"
                   width="491"
                   height="311"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_table_locks.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_table_locks-day"
                   alt="Table locks"
                       width="491"
                   height="287"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_table_locks.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_table_locks-week"
                   alt="Table locks"
                   width="491"
                   height="287"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="mysql_tmp_tables.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_tmp_tables-day"
                   alt="Temporary objects"
                       width="491"
                   height="299"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="mysql_tmp_tables.html">
                  <img class="img-responsive i"
                   src="image.php?mysql_tmp_tables-week"
                   alt="Temporary objects"
                   width="491"
                   height="299"/>
                </a>
              </div>
            </div>

        </div>

        <div class="tab-pane fade " id="network">

            <div class="row">
              <div class="col-md-6">
                <a href="fw_conntrack.html">
                  <img class="img-responsive i"
                   src="image.php?fw_conntrack-day"
                   alt="Connections through firewall"
                       width="491"
                   height="347"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="fw_conntrack.html">
                  <img class="img-responsive i"
                   src="image.php?fw_conntrack-week"
                   alt="Connections through firewall"
                   width="491"
                   height="347"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="fw_packets.html">
                  <img class="img-responsive i"
                   src="image.php?fw_packets-day"
                   alt="Firewall Throughput"
                       width="491"
                   height="287"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="fw_packets.html">
                  <img class="img-responsive i"
                   src="image.php?fw_packets-week"
                   alt="Firewall Throughput"
                   width="491"
                   height="287"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="fw_forwarded_local.html">
                  <img class="img-responsive i"
                   src="image.php?fw_forwarded_local-day"
                   alt="ipconntrack"
                       width="491"
                   height="287"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="fw_forwarded_local.html">
                  <img class="img-responsive i"
                   src="image.php?fw_forwarded_local-week"
                   alt="ipconntrack"
                   width="491"
                   height="287"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="netstat.html">
                  <img class="img-responsive i"
                   src="image.php?netstat-day"
                   alt="Netstat"
                       width="491"
                   height="323"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="netstat.html">
                  <img class="img-responsive i"
                   src="image.php?netstat-week"
                   alt="Netstat"
                   width="491"
                   height="323"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="if_err_tun0.html">
                  <img class="img-responsive i"
                   src="image.php?if_err_tun0-day"
                   alt="tun0 errors"
                       width="491"
                   height="299"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="if_err_tun0.html">
                  <img class="img-responsive i"
                   src="image.php?if_err_tun0-week"
                   alt="tun0 errors"
                   width="491"
                   height="299"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="if_tun0.html">
                  <img class="img-responsive i"
                   src="image.php?if_tun0-day"
                   alt="tun0 traffic"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="if_tun0.html">
                  <img class="img-responsive i"
                   src="image.php?if_tun0-week"
                   alt="tun0 traffic"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="if_err_venet0.html">
                  <img class="img-responsive i"
                   src="image.php?if_err_venet0-day"
                   alt="venet0 errors"
                       width="491"
                   height="299"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="if_err_venet0.html">
                  <img class="img-responsive i"
                   src="image.php?if_err_venet0-week"
                   alt="venet0 errors"
                   width="491"
                   height="299"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="if_venet0.html">
                  <img class="img-responsive i"
                   src="image.php?if_venet0-day"
                   alt="venet0 traffic"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="if_venet0.html">
                  <img class="img-responsive i"
                   src="image.php?if_venet0-week"
                   alt="venet0 traffic"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

        </div>

        <div class="tab-pane fade " id="nginx">

            <div class="row">
              <div class="col-md-6">
                <a href="nginx_request.html">
                  <img class="img-responsive i"
                   src="image.php?nginx_request-day"
                   alt="Nginx requests"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="nginx_request.html">
                  <img class="img-responsive i"
                   src="image.php?nginx_request-week"
                   alt="Nginx requests"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="nginx_status.html">
                  <img class="img-responsive i"
                   src="image.php?nginx_status-day"
                   alt="NGINX status"
                       width="491"
                   height="311"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="nginx_status.html">
                  <img class="img-responsive i"
                   src="image.php?nginx_status-week"
                   alt="NGINX status"
                   width="491"
                   height="311"/>
                </a>
              </div>
            </div>

        </div>

        <div class="tab-pane fade " id="postfix">

            <div class="row">
              <div class="col-md-6">
                <a href="postfix_mailvolume.html">
                  <img class="img-responsive i"
                   src="image.php?postfix_mailvolume-day"
                   alt="Postfix bytes throughput"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="postfix_mailvolume.html">
                  <img class="img-responsive i"
                   src="image.php?postfix_mailvolume-week"
                   alt="Postfix bytes throughput"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="postfix_mailqueue.html">
                  <img class="img-responsive i"
                   src="image.php?postfix_mailqueue-day"
                   alt="Postfix Mailqueue"
                       width="491"
                   height="347"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="postfix_mailqueue.html">
                  <img class="img-responsive i"
                   src="image.php?postfix_mailqueue-week"
                   alt="Postfix Mailqueue"
                   width="491"
                   height="347"/>
                </a>
              </div>
            </div>

        </div>

        <div class="tab-pane fade " id="processes">

            <div class="row">
              <div class="col-md-6">
                <a href="forks.html">
                  <img class="img-responsive i"
                   src="image.php?forks-day"
                   alt="Fork rate"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="forks.html">
                  <img class="img-responsive i"
                   src="image.php?forks-week"
                   alt="Fork rate"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="threads.html">
                  <img class="img-responsive i"
                   src="image.php?threads-day"
                   alt="Number of threads"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="threads.html">
                  <img class="img-responsive i"
                   src="image.php?threads-week"
                   alt="Number of threads"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="processes.html">
                  <img class="img-responsive i"
                   src="image.php?processes-day"
                   alt="Processes"
                       width="491"
                   height="359"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="processes.html">
                  <img class="img-responsive i"
                   src="image.php?processes-week"
                   alt="Processes"
                   width="491"
                   height="359"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="proc_pri.html">
                  <img class="img-responsive i"
                   src="image.php?proc_pri-day"
                   alt="Processes priority"
                       width="491"
                   height="299"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="proc_pri.html">
                  <img class="img-responsive i"
                   src="image.php?proc_pri-week"
                   alt="Processes priority"
                   width="491"
                   height="299"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="vmstat.html">
                  <img class="img-responsive i"
                   src="image.php?vmstat-day"
                   alt="VMstat"
                       width="491"
                   height="287"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="vmstat.html">
                  <img class="img-responsive i"
                   src="image.php?vmstat-week"
                   alt="VMstat"
                   width="491"
                   height="287"/>
                </a>
              </div>
            </div>

        </div>

        <div class="tab-pane fade " id="samba">

            <div class="row">
              <div class="col-md-6">
                <a href="samba.html">
                  <img class="img-responsive i"
                   src="image.php?samba-day"
                   alt="Samba status"
                       width="491"
                   height="299"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="samba.html">
                  <img class="img-responsive i"
                   src="image.php?samba-week"
                   alt="Samba status"
                   width="491"
                   height="299"/>
                </a>
              </div>
            </div>

        </div>

        <div class="tab-pane fade " id="system">

            <div class="row">
              <div class="col-md-6">
                <a href="entropy.html">
                  <img class="img-responsive i"
                   src="image.php?entropy-day"
                   alt="Available entropy"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="entropy.html">
                  <img class="img-responsive i"
                   src="image.php?entropy-week"
                   alt="Available entropy"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="cpu.html">
                  <img class="img-responsive i"
                   src="image.php?cpu-day"
                   alt="CPU usage"
                       width="491"
                   height="359"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="cpu.html">
                  <img class="img-responsive i"
                   src="image.php?cpu-week"
                   alt="CPU usage"
                   width="491"
                   height="359"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="open_files.html">
                  <img class="img-responsive i"
                   src="image.php?open_files-day"
                   alt="File table usage"
                       width="491"
                   height="287"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="open_files.html">
                  <img class="img-responsive i"
                   src="image.php?open_files-week"
                   alt="File table usage"
                   width="491"
                   height="287"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="open_inodes.html">
                  <img class="img-responsive i"
                   src="image.php?open_inodes-day"
                   alt="Inode table usage"
                       width="491"
                   height="287"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="open_inodes.html">
                  <img class="img-responsive i"
                   src="image.php?open_inodes-week"
                   alt="Inode table usage"
                   width="491"
                   height="287"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="interrupts.html">
                  <img class="img-responsive i"
                   src="image.php?interrupts-day"
                   alt="Interrupts and context switches"
                       width="491"
                   height="287"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="interrupts.html">
                  <img class="img-responsive i"
                   src="image.php?interrupts-week"
                   alt="Interrupts and context switches"
                   width="491"
                   height="287"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="load.html">
                  <img class="img-responsive i"
                   src="image.php?load-day"
                   alt="Load average"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="load.html">
                  <img class="img-responsive i"
                   src="image.php?load-week"
                   alt="Load average"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="users.html">
                  <img class="img-responsive i"
                   src="image.php?users-day"
                   alt="Logged in users"
                       width="491"
                   height="323"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="users.html">
                  <img class="img-responsive i"
                   src="image.php?users-week"
                   alt="Logged in users"
                   width="491"
                   height="323"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="memory.html">
                  <img class="img-responsive i"
                   src="image.php?memory-day"
                   alt="Memory usage"
                       width="491"
                   height="359"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="memory.html">
                  <img class="img-responsive i"
                   src="image.php?memory-week"
                   alt="Memory usage"
                   width="491"
                   height="359"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="swap.html">
                  <img class="img-responsive i"
                   src="image.php?swap-day"
                   alt="Swap in/out"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="swap.html">
                  <img class="img-responsive i"
                   src="image.php?swap-week"
                   alt="Swap in/out"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <a href="uptime.html">
                  <img class="img-responsive i"
                   src="image.php?uptime-day"
                   alt="Uptime"
                       width="491"
                   height="275"/>
                </a>
              </div>
              <div class="col-md-6">
                <a href="uptime.html">
                  <img class="img-responsive i"
                   src="image.php?uptime-week"
                   alt="Uptime"
                   width="491"
                   height="275"/>
                </a>
              </div>
            </div>

        </div>

    </div>

	</div>

    <div style="margin-top: 20px;" class="container">
      <div class="well well-sm">
        <small>This page was generated by <a href="http://www.munin-monitoring.org/">Munin</a> version 2.0.25 at 2016-02-03 21:50:17+0800 (HKT) with <a href="https://github.com/jonnymccullagh/munstrap">MunStrap</a> template.</small>
      </div>
    </div>

    <script src="../../static/js/bootstrap.min.js"></script>
    <script src="../../static/js/munstrap.js"></script>
    <script type="text/javascript">
    </script>
  </body>
</html>



